package gui.Interfaces.MainMenu;

import javafx.embed.swing.SwingNode;
import javafx.event.EventHandler;
import javafx.fxml.FXMLLoader;
import javafx.scene.Cursor;
import javafx.scene.control.Label;
import javafx.scene.control.Tab;
import javafx.scene.input.ScrollEvent;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;
import tracer.Tracer;
import tracer.math.Delta;

import java.io.IOException;

public class TraceController {

    //FXML
    public Label grblX;
    public Label grblY;
    public Label grblZ;
    public Label grblA;
    public SwingNode swingNodeTrace;
    
    public static TraceController controller;
    
    
    public void initialize()
    {
        controller = this;
        Tracer.setup(swingNodeTrace);
        
        // These can be generated by grbl
        //TODO these are just test values
        setGrblX(1.0);
        setGrblY(8.15465422);
        setGrblZ(1.57);
        setGrblA(55.0);
    }
    
    public static Tab setup()
    {
        try {
            Tab tabThird = (FXMLLoader.load(TraceController.class.getResource("Trace.fxml")));
        
            BorderPane pane = (BorderPane) tabThird.getContent();
            AnchorPane anchor = (AnchorPane) pane.getChildren().get(0);
            BorderPane anchorPane = (BorderPane) anchor.getChildren().get(0);
            SwingNode node = (SwingNode) anchorPane.getChildren().get(0);
            
            final Delta delta = new Delta();
            node.setOnMousePressed(mouseEvent -> {
                delta.x = mouseEvent.getSceneX();
                delta.y = mouseEvent.getSceneY();
                node.setCursor(Cursor.MOVE);
            });
            node.setOnMouseReleased(mouseEvent -> node.setCursor(Cursor.HAND));
            node.setOnMouseDragged(mouseEvent -> {
                Tracer.handleCameraControl(mouseEvent.getSceneX() - delta.x, mouseEvent.getSceneY() - delta.y);
                delta.x = mouseEvent.getSceneX();
                delta.y = mouseEvent.getSceneY();
            });
            node.setOnMouseEntered(mouseEvent -> node.setCursor(Cursor.HAND));
            node.setOnScroll(
                    new EventHandler<ScrollEvent>() {
                        @Override
                        public void handle(ScrollEvent event) {
                            Tracer.handleCameraZoom(event.getDeltaY());
                        }
                    });
            
            return tabThird;
            
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }
    
    
    public static void addTrace(double x, double y, double z)
    {
        Tracer.addTrace(x, y, z);
    }
    
    
    public static void setGrblX(double x) {
        controller.grblX.setText(String.format("X Position: %.2f", x));
    }
    
    public static void setGrblY(double y) {
        controller.grblY.setText(String.format("Y Position: %.2f", y));
    }
    
    public static void setGrblZ(double z) {
        controller.grblZ.setText(String.format("Z Position: %.2f", z));
    }
    
    public static void setGrblA(double a) {
        controller.grblA.setText(String.format("Acceleration: %.2f", a));
    }
    
    
}
